sudo: true
language: C++
os:
  - linux
  - osx
 
compiler:
  - g++
  - clang++

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  sudo apt-get install -y libhdf5-dev libhdf5-serial-dev libmysqlclient-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      python3-config --prefix;
      ln -s /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/include/python3.6m /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/include/python3.6;
      ls /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/include/python3.6;
      brew install libiconv mysql-client hdf5; 
      brew link --overwrite gcc; 
    fi  
  - git clone --branch=dev https://github.com/tboox/xmake.git tboox/xmake --depth 1
  - cd ./tboox/xmake
  - ./scripts/get.sh __local__
  - cd
  - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
  - tar -jxf boost_1_67_0.tar.bz2
  - cd boost_1_67_0
  - ./bootstrap.sh --with-python=python3
  - ./b2 release link=shared --with-date_time --with-filesystem --with-system --with-serialization --with-python --with-test
  - ls ./stage/lib
  - cd ..

script:
  - cd ./build/fasiondog/hikyuu
  - export BOOST_ROOT=$HOME/boost_1_67_0;
  - export BOOST_LIB=$HOME/boost_1_67_0/stage/lib
  - xmake f --with-unit-test=y --cxx=$CXX
  - xmake
  - xmake r unit-test
  
