name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@master
    - name: build
      env:
        CI: yes
      run: |
        git submodule updata --init --recursive
        Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/xmake-io/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
        xmake f --confirm=y --test=small
        xmake -b small-test
        xmake r small-test
      shell: pwsh
