name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2016
    
    steps:
    - uses: actions/checkout@master
    - name: install xmake
      run: powershell Invoke-Webrequest "https://raw.githubusercontent.com/tboox/xmake/dev/scripts/get.ps1"
    - name: xmake
      run: xmake --version
