name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@master
    - name: install xmake
      env:
        CI: yes
      run: |
        Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/xmake-io/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
        ls
      shell: pwsh
    - name: build boost
      run: |
        cd $env:BOOST_ROOT
        ls
        bootstrap.bat
        b2 release link=shared address-model=64 -j 4 --with-python --with-date_time --with-filesystem --with-system --with-serialization --with-test
      
