name: win-build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    
    steps:
    - uses: xmake-io/github-action-setup-xmake@v1
    - name: prepare
      run: | 
        git clone https://github.com/fasiondog/hikyuu.git --recursive --depth 1
        Invoke-WebRequest "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.zip" -UseBasicParsing -OutFile ./boost_1_74_0.zip
        Expand-Archive ./boost_1_74_0.zip -DestinationPath .
        Copy-Item ./boost_1_74_0 ./hikyuu
        cd ./hikyuu
        ./bootstrap.bat --with-python=python3
    - name: build
      run: |
        python --version
        cd hikyuu
        pip install click
        python setup.py build
    - name: test
      run: |
        cd hikyuu
        python setup.py test
