name: ubuntu-aarch64-build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cross: [aarch64-linux-musl]

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Cross-Musl-${{ matrix.cross }}
        cancel-in-progress: true
    
    steps:
    - uses: xmake-io/github-action-setup-xmake@v1
    - name: Installation xmake
      run: |
        wget https://github.com/xmake-mirror/musl.cc/releases/download/20210202/${{ matrix.cross }}-cross.linux.tgz
        tar -xvf ${{ matrix.cross }}-cross.linux.tgz

    - name: checkout
      run: | 
        git clone https://github.com/fasiondog/hikyuu.git --recursive --depth 1
        
    - name: build
      run: |
        cd ./hikyuu
        xmake f -p cross -a aarch64 --sdk=`pwd`/${{ matrix.cross }}-cross -y
        xmake -b small-test