name: ubuntu-python-build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v4      
    - uses: xmake-io/github-action-setup-xmake@v1

    - name: Cache packages
      id: cache-xmake-ubuntu
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.xmake
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: configure
      run: |
        xmake f -y

    - name: build
      run: |
        xmake -b core
