name: win-build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    
    steps:
    - uses: xmake-io/github-action-setup-xmake@v1
    - name: checkout
      run: | 
        git clone https://github.com/fasiondog/hikyuu.git --recursive --depth 1
    - name: download_boost
      run: | 
        Invoke-WebRequest "https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.zip" -UseBasicParsing -OutFile ./boost_1_75_0.zip
        Expand-Archive ./boost_1_75_0.zip -DestinationPath ./hikyuu
        # Copy-Item ./boost_1_75_0 ./hikyuu
   
    - name: build
      shell: cmd
      run: |
        cd hikyuu
        xmake f -y
        xmake -b small-test
        xmake r small-test
